import { createContext, useContext, useMemo, useState } from "react";

const STORAGE_KEY = "e_prescription_lang";

const translations = {
  en: {
    appLang: "Language",
    langUz: "Uzbek",
    langRu: "Russian",
    langEn: "English",
    roleAdmin: "Admin",
    roleDoctor: "Doctor",
    rolePharmacy: "Pharmacy",
    rolePatient: "Patient",
    loadingSession: "Loading session",
    preparingWorkspace: "Preparing your workspace...",
    pageNotFound: "Page not found",
    pageNotFoundDesc: "The page you requested does not exist.",
    goHome: "Go home",
    qrEyebrow: "QR-based E-Prescription",
    loginHeroEyebrow: "Paperless workflow",
    loginHeroTitle: "Electronic prescription system",
    loginHeroDescription:
      "Doctors create prescriptions, patients receive QR codes, and pharmacies verify them quickly while blocking reuse.",
    home: "Home",
    logout: "Logout",
    loginTitle: "Login",
    loginDesc: "Systemga rol bo'yicha kiring.",
    email: "Email",
    password: "Password",
    loginBtn: "Login",
    loginLoading: "Logging in...",
    noAccount: "No account yet?",
    createOne: "Create one",
    registerTitle: "Register",
    registerDesc: "Doctor, pharmacy yoki patient akkaunt yarating.",
    registerHeroEyebrow: "Role-based access",
    registerHeroTitle: "Create your account",
    registerHeroDescription:
      "If you register as a patient and your email matches the one entered by the doctor, prescriptions can link to your account automatically.",
    fullName: "Full name",
    role: "Role",
    createAccount: "Create account",
    creating: "Creating...",
    hasAccount: "Already registered?",
    goLogin: "Go to login",
    doctorDashboard: "Doctor Dashboard",
    doctorDashboardDesc:
      "Add patient profiles, create prescriptions, and deliver a QR-ready payload for pharmacy validation.",
    addPatient: "Add Patient",
    addPatientDesc:
      "You can register a patient profile before creating a prescription.",
    name: "Name",
    age: "Age",
    savePatient: "Save patient",
    saving: "Saving...",
    createPrescription: "Create Prescription",
    createPrescriptionDesc:
      "Choose a patient and describe the prescribed medications.",
    patient: "Patient",
    selectPatient: "Select patient",
    createPrescriptionBtn: "Create prescription",
    generating: "Generating...",
    latestQr: "Latest QR",
    latestQrDesc:
      "The most recent prescription is shown with its QR payload for testing and delivery.",
    noPrescriptionYet:
      "No prescription created yet. Create one to display its QR code here.",
    prescriptionHistory: "Prescription History",
    prescriptionHistoryDesc: "Search by patient name or prescription id.",
    search: "Search",
    searchPlaceholder: "Search prescriptions",
    loadingDashboard: "Loading dashboard...",
    showQr: "Show QR",
    noSearchMatch: "No prescriptions matched your search.",
    medication: "Medication",
    remove: "Remove",
    dosage: "Dosage",
    instructions: "Instructions",
    addMedication: "Add medication",
    pharmacyDashboard: "Pharmacy Dashboard",
    pharmacyDashboardDesc:
      "Pharmacy staff can validate a QR payload, inspect medication details, and mark the prescription as used.",
    verifyQrPayload: "Verify QR Payload",
    verifyQrPayloadDesc:
      "A real QR scanner would decode the payload and paste the token below.",
    token: "Token",
    tokenPlaceholder: "Paste QR payload token here",
    verify: "Verify",
    checking: "Checking...",
    clear: "Clear",
    prescriptionResult: "Prescription Result",
    prescriptionResultDesc:
      "Once verified, you can confirm dispensing and lock the prescription against reuse.",
    confirmDispense: "Confirm dispense",
    updating: "Updating...",
    scanOrPaste: "Scan or paste a QR payload to preview the prescription here.",
    patientDashboard: "Patient Dashboard",
    patientDashboardDesc:
      "Patients can view their prescriptions, inspect medication instructions, and present the QR code at a pharmacy.",
    myPrescriptions: "My Prescriptions",
    myPrescriptionsDesc:
      "If your account email matches the patient record added by the doctor, your prescriptions will appear here.",
    loadingPrescriptions: "Loading prescriptions...",
    noLinkedPrescriptions: "No prescriptions are linked to your account yet.",
    statsPatients: "Patients",
    statsPrescriptions: "Prescriptions",
    statsActive: "Active",
    statsUsed: "Used",
    statsTotalPrescriptions: "Total prescriptions",
    unknownPatient: "Unknown patient",
    created: "Created",
    doctor: "Doctor",
    usedAt: "Used at",
    medications: "Medications",
    qrPayloadToken: "QR payload token",
    notLinked: "Not linked",
    patientSaved: "Patient saved successfully.",
    prescriptionCreated: "Prescription created and QR generated.",
    adminDashboard: "Admin Dashboard",
    adminDashboardDesc:
      "Manage users, approvals, prescriptions, and system audit activity from one place.",
    adminSystemTools: "System Tools",
    adminSystemToolsDesc:
      "Refresh the control panel data and repair patient-account links by email.",
    adminRefreshData: "Refresh data",
    adminSyncPatients: "Sync patient links",
    adminPendingApprovals: "Pending approvals",
    adminPendingApprovalsDesc:
      "Approve newly registered doctors and pharmacies before they enter the workflow.",
    adminNoPendingApprovals: "No users are waiting for approval right now.",
    adminUserManagement: "User Management",
    adminUserManagementDesc:
      "Search users, change roles, approve access, block accounts, and reset passwords.",
    adminUserSearchPlaceholder: "Search by name or login",
    adminApplyFilters: "Apply filters",
    adminAllRoles: "All roles",
    adminAnyStatus: "Any status",
    adminAnyApproval: "Any approval",
    adminStatus: "Status",
    adminStatusActive: "Active",
    adminStatusBlocked: "Blocked",
    adminApproval: "Approval",
    adminApproved: "Approved",
    adminPending: "Pending",
    adminSaveChanges: "Save changes",
    adminResetPassword: "Reset password",
    adminPasswordPlaceholder: "New password",
    adminCreatedOn: "Created",
    adminNoUsersFound: "No users matched your filters.",
    adminPrescriptionOverview: "Prescription Overview",
    adminPrescriptionOverviewDesc:
      "Review any prescription in the system and filter by status or search terms.",
    adminPrescriptionStatus: "Prescription status",
    adminAllStatuses: "All statuses",
    adminNoPrescriptionsFound: "No prescriptions matched your filters.",
    adminAuditLogs: "Audit Logs",
    adminAuditLogsDesc:
      "Track registrations, approvals, verification activity, password resets, and other system events.",
    adminNoLogs: "No audit events yet.",
    adminSystem: "System",
    adminTotalUsers: "Users",
    adminBlockedUsers: "Blocked",
  },
  uz: {
    appLang: "Til",
    langUz: "O'zbek",
    langRu: "Rus",
    langEn: "Ingliz",
    roleAdmin: "Admin",
    roleDoctor: "Shifokor",
    rolePharmacy: "Dorixona",
    rolePatient: "Bemor",
    loadingSession: "Sessiya yuklanmoqda",
    preparingWorkspace: "Ish muhiti tayyorlanmoqda...",
    pageNotFound: "Sahifa topilmadi",
    pageNotFoundDesc: "So‘ralgan sahifa mavjud emas.",
    goHome: "Bosh sahifa",
    qrEyebrow: "QR asosidagi E-Retsept",
    loginHeroEyebrow: "Qog'ozsiz jarayon",
    loginHeroTitle: "Elektron retseptlar tizimi",
    loginHeroDescription:
      "Shifokor retsept yaratadi, bemor QR kodni oladi, dorixona esa uni tez tekshiradi va qayta ishlatishni bloklaydi.",
    home: "Bosh sahifa",
    logout: "Chiqish",
    loginTitle: "Kirish",
    loginDesc: "Tizimga rol bo'yicha kiring.",
    email: "Email",
    password: "Parol",
    loginBtn: "Kirish",
    loginLoading: "Kirilmoqda...",
    noAccount: "Akkaunt yo'qmi?",
    createOne: "Yaratish",
    registerTitle: "Ro'yxatdan o'tish",
    registerDesc: "Shifokor, dorixona yoki bemor akkauntini yarating.",
    registerHeroEyebrow: "Rolga asoslangan kirish",
    registerHeroTitle: "Akkauntingizni yarating",
    registerHeroDescription:
      "Agar bemor rolida ro'yxatdan o'tsangiz va emailingiz shifokor kiritgan email bilan mos kelsa, retseptlar akkauntingizga avtomatik bog'lanadi.",
    fullName: "To'liq ism",
    role: "Rol",
    createAccount: "Akkaunt yaratish",
    creating: "Yaratilmoqda...",
    hasAccount: "Akkauntingiz bormi?",
    goLogin: "Kirishga o'tish",
    doctorDashboard: "Shifokor paneli",
    doctorDashboardDesc:
      "Bemor profillarini qo‘shing, retsept yarating va dorixona tekshiruvi uchun QR tayyorlang.",
    addPatient: "Bemor qo'shish",
    addPatientDesc: "Retseptdan oldin bemor profilini ro'yxatdan o'tkazing.",
    name: "Ism",
    age: "Yosh",
    savePatient: "Bemorni saqlash",
    saving: "Saqlanmoqda...",
    createPrescription: "Retsept yaratish",
    createPrescriptionDesc: "Bemorni tanlang va dorilarni kiriting.",
    patient: "Bemor",
    selectPatient: "Bemorni tanlang",
    createPrescriptionBtn: "Retsept yaratish",
    generating: "Yaratilmoqda...",
    latestQr: "So'nggi QR",
    latestQrDesc:
      "Sinov va yetkazish uchun eng so‘nggi retseptning QR ma’lumoti ko‘rsatiladi.",
    noPrescriptionYet:
      "Hali retsept yaratilmagan. QR ko‘rish uchun retsept yarating.",
    prescriptionHistory: "Retseptlar tarixi",
    prescriptionHistoryDesc: "Bemor ismi yoki retsept ID bo‘yicha qidiring.",
    search: "Qidiruv",
    searchPlaceholder: "Retseptlarni qidiring",
    loadingDashboard: "Panel yuklanmoqda...",
    showQr: "QR ko'rsatish",
    noSearchMatch: "Qidiruvga mos retsept topilmadi.",
    medication: "Dori",
    remove: "O'chirish",
    dosage: "Doza",
    instructions: "Ko'rsatma",
    addMedication: "Dori qo'shish",
    pharmacyDashboard: "Dorixona paneli",
    pharmacyDashboardDesc:
      "Dorixona xodimi QR tokenni tekshiradi va retseptni ishlatilgan deb belgilaydi.",
    verifyQrPayload: "QR tokenni tekshirish",
    verifyQrPayloadDesc:
      "Haqiqiy skaner tokenni ochib beradi, quyiga shu tokenni joylaysiz.",
    token: "Token",
    tokenPlaceholder: "QR tokenni shu yerga qo'ying",
    verify: "Tekshirish",
    checking: "Tekshirilmoqda...",
    clear: "Tozalash",
    prescriptionResult: "Retsept natijasi",
    prescriptionResultDesc:
      "Tekshiruvdan so‘ng berilganini tasdiqlang va qayta ishlatishni bloklang.",
    confirmDispense: "Berishni tasdiqlash",
    updating: "Yangilanmoqda...",
    scanOrPaste: "Bu yerda ko‘rish uchun QR tokenni skaner qiling yoki qo‘ying.",
    patientDashboard: "Bemor paneli",
    patientDashboardDesc:
      "Bemor o‘z retseptlarini ko‘radi va dorixonada QR kodni ko‘rsatadi.",
    myPrescriptions: "Mening retseptlarim",
    myPrescriptionsDesc:
      "Akkaunt emailingiz shifokor kiritgan email bilan mos bo‘lsa, retseptlar shu yerda chiqadi.",
    loadingPrescriptions: "Retseptlar yuklanmoqda...",
    noLinkedPrescriptions: "Akkauntingizga bog‘langan retseptlar hozircha yo‘q.",
    statsPatients: "Bemorlar",
    statsPrescriptions: "Retseptlar",
    statsActive: "Faol",
    statsUsed: "Ishlatilgan",
    statsTotalPrescriptions: "Jami retseptlar",
    unknownPatient: "Noma'lum bemor",
    created: "Yaratilgan",
    doctor: "Shifokor",
    usedAt: "Ishlatilgan vaqt",
    medications: "Dorilar",
    qrPayloadToken: "QR token",
    notLinked: "Bog'lanmagan",
    patientSaved: "Bemor muvaffaqiyatli saqlandi.",
    prescriptionCreated: "Retsept yaratildi va QR hosil qilindi.",
    adminDashboard: "Admin paneli",
    adminDashboardDesc:
      "Foydalanuvchilar, tasdiqlar, retseptlar va tizim loglarini bitta joydan boshqaring.",
    adminSystemTools: "Tizim vositalari",
    adminSystemToolsDesc:
      "Panel ma'lumotlarini yangilang va email bo'yicha patient-account linklarini tiklang.",
    adminRefreshData: "Ma'lumotni yangilash",
    adminSyncPatients: "Bemor linklarini sinxronlash",
    adminPendingApprovals: "Kutilayotgan tasdiqlar",
    adminPendingApprovalsDesc:
      "Yangi ro'yxatdan o'tgan shifokor va dorixonalarni ish jarayoniga kirishidan oldin tasdiqlang.",
    adminNoPendingApprovals: "Hozircha tasdiq kutayotgan foydalanuvchi yo'q.",
    adminUserManagement: "Foydalanuvchilar boshqaruvi",
    adminUserManagementDesc:
      "User'larni qidiring, rolini o'zgartiring, ruxsat bering, bloklang va parolini almashtiring.",
    adminUserSearchPlaceholder: "Ism yoki login bo'yicha qidiring",
    adminApplyFilters: "Filtrlarni qo'llash",
    adminAllRoles: "Barcha rollar",
    adminAnyStatus: "Har qanday status",
    adminAnyApproval: "Har qanday tasdiq",
    adminStatus: "Holat",
    adminStatusActive: "Faol",
    adminStatusBlocked: "Bloklangan",
    adminApproval: "Tasdiq",
    adminApproved: "Tasdiqlangan",
    adminPending: "Kutilmoqda",
    adminSaveChanges: "O'zgarishni saqlash",
    adminResetPassword: "Parolni almashtirish",
    adminPasswordPlaceholder: "Yangi parol",
    adminCreatedOn: "Yaratilgan",
    adminNoUsersFound: "Filtrlarga mos foydalanuvchi topilmadi.",
    adminPrescriptionOverview: "Retseptlar ko'rinishi",
    adminPrescriptionOverviewDesc:
      "Tizimdagi istalgan retseptni ko'ring va holat yoki qidiruv bo'yicha filtrlab chiqing.",
    adminPrescriptionStatus: "Retsept holati",
    adminAllStatuses: "Barcha holatlar",
    adminNoPrescriptionsFound: "Filtrlarga mos retsept topilmadi.",
    adminAuditLogs: "Audit loglar",
    adminAuditLogsDesc:
      "Ro'yxatdan o'tish, tasdiqlash, verify, parol almashtirish va boshqa tizim voqealarini kuzating.",
    adminNoLogs: "Hozircha audit yozuvlari yo'q.",
    adminSystem: "Tizim",
    adminTotalUsers: "Foydalanuvchilar",
    adminBlockedUsers: "Bloklanganlar",
  },
  ru: {
    appLang: "Язык",
    langUz: "Узбекский",
    langRu: "Русский",
    langEn: "Английский",
    roleAdmin: "Админ",
    roleDoctor: "Врач",
    rolePharmacy: "Аптека",
    rolePatient: "Пациент",
    loadingSession: "Загрузка сессии",
    preparingWorkspace: "Подготовка рабочего пространства...",
    pageNotFound: "Страница не найдена",
    pageNotFoundDesc: "Запрошенная страница не существует.",
    goHome: "На главную",
    qrEyebrow: "QR электронный рецепт",
    loginHeroEyebrow: "Безбумажный процесс",
    loginHeroTitle: "Система электронных рецептов",
    loginHeroDescription:
      "Врач создает рецепт, пациент получает QR-код, а аптека быстро проверяет его и блокирует повторное использование.",
    home: "Главная",
    logout: "Выйти",
    loginTitle: "Вход",
    loginDesc: "Войдите в систему по роли.",
    email: "Email",
    password: "Пароль",
    loginBtn: "Войти",
    loginLoading: "Вход...",
    noAccount: "Нет аккаунта?",
    createOne: "Создать",
    registerTitle: "Регистрация",
    registerHeroEyebrow: "Доступ по ролям",
    registerHeroTitle: "Создайте аккаунт",
    registerHeroDescription:
      "Если вы регистрируетесь как пациент и ваш email совпадает с email, указанным врачом, рецепты смогут автоматически привязаться к аккаунту.",
    registerDesc: "Создайте аккаунт врача, аптеки или пациента.",
    fullName: "Полное имя",
    role: "Роль",
    createAccount: "Создать аккаунт",
    creating: "Создание...",
    hasAccount: "Уже зарегистрированы?",
    goLogin: "Перейти ко входу",
    doctorDashboard: "Панель врача",
    doctorDashboardDesc:
      "Добавляйте пациентов, создавайте рецепты и выдавайте QR для проверки в аптеке.",
    addPatient: "Добавить пациента",
    addPatientDesc: "Перед созданием рецепта можно добавить профиль пациента.",
    name: "Имя",
    age: "Возраст",
    savePatient: "Сохранить пациента",
    saving: "Сохранение...",
    createPrescription: "Создать рецепт",
    createPrescriptionDesc: "Выберите пациента и заполните лекарства.",
    patient: "Пациент",
    selectPatient: "Выберите пациента",
    createPrescriptionBtn: "Создать рецепт",
    generating: "Создание...",
    latestQr: "Последний QR",
    latestQrDesc:
      "Показан последний рецепт с QR-данными для проверки и выдачи.",
    noPrescriptionYet:
      "Пока нет рецептов. Создайте рецепт, чтобы увидеть QR-код.",
    prescriptionHistory: "История рецептов",
    prescriptionHistoryDesc: "Поиск по имени пациента или ID рецепта.",
    search: "Поиск",
    searchPlaceholder: "Искать рецепты",
    loadingDashboard: "Загрузка панели...",
    showQr: "Показать QR",
    noSearchMatch: "Рецепты по запросу не найдены.",
    medication: "Лекарство",
    remove: "Удалить",
    dosage: "Дозировка",
    instructions: "Инструкция",
    addMedication: "Добавить лекарство",
    pharmacyDashboard: "Панель аптеки",
    pharmacyDashboardDesc:
      "Сотрудник аптеки проверяет QR-токен и отмечает рецепт как использованный.",
    verifyQrPayload: "Проверка QR-токена",
    verifyQrPayloadDesc:
      "Сканер декодирует токен, вставьте его в поле ниже.",
    token: "Токен",
    tokenPlaceholder: "Вставьте QR-токен сюда",
    verify: "Проверить",
    checking: "Проверка...",
    clear: "Очистить",
    prescriptionResult: "Результат рецепта",
    prescriptionResultDesc:
      "После проверки подтвердите выдачу и заблокируйте повторное использование.",
    confirmDispense: "Подтвердить выдачу",
    updating: "Обновление...",
    scanOrPaste: "Отсканируйте или вставьте QR-токен для предпросмотра.",
    patientDashboard: "Панель пациента",
    patientDashboardDesc:
      "Пациент видит свои рецепты и показывает QR-код в аптеке.",
    myPrescriptions: "Мои рецепты",
    myPrescriptionsDesc:
      "Если email аккаунта совпадает с email в профиле пациента, рецепты появятся здесь.",
    loadingPrescriptions: "Загрузка рецептов...",
    noLinkedPrescriptions: "К вашему аккаунту пока не привязаны рецепты.",
    statsPatients: "Пациенты",
    statsPrescriptions: "Рецепты",
    statsActive: "Активные",
    statsUsed: "Использовано",
    statsTotalPrescriptions: "Всего рецептов",
    unknownPatient: "Неизвестный пациент",
    created: "Создан",
    doctor: "Врач",
    usedAt: "Использован",
    medications: "Лекарства",
    qrPayloadToken: "QR токен",
    notLinked: "Не привязан",
    patientSaved: "Пациент успешно сохранен.",
    prescriptionCreated: "Рецепт создан, QR сгенерирован.",
    adminDashboard: "Панель администратора",
    adminDashboardDesc:
      "Управляйте пользователями, подтверждениями, рецептами и журналом действий из одного места.",
    adminSystemTools: "Системные инструменты",
    adminSystemToolsDesc:
      "Обновляйте данные панели и восстанавливайте связи patient-account по email.",
    adminRefreshData: "Обновить данные",
    adminSyncPatients: "Синхронизировать связи пациентов",
    adminPendingApprovals: "Ожидают подтверждения",
    adminPendingApprovalsDesc:
      "Подтверждайте новых врачей и аптеки перед допуском к системе.",
    adminNoPendingApprovals: "Сейчас нет пользователей, ожидающих подтверждения.",
    adminUserManagement: "Управление пользователями",
    adminUserManagementDesc:
      "Ищите пользователей, меняйте роли, подтверждайте доступ, блокируйте и сбрасывайте пароли.",
    adminUserSearchPlaceholder: "Поиск по имени или логину",
    adminApplyFilters: "Применить фильтры",
    adminAllRoles: "Все роли",
    adminAnyStatus: "Любой статус",
    adminAnyApproval: "Любое подтверждение",
    adminStatus: "Статус",
    adminStatusActive: "Активен",
    adminStatusBlocked: "Заблокирован",
    adminApproval: "Подтверждение",
    adminApproved: "Подтвержден",
    adminPending: "Ожидает",
    adminSaveChanges: "Сохранить изменения",
    adminResetPassword: "Сбросить пароль",
    adminPasswordPlaceholder: "Новый пароль",
    adminCreatedOn: "Создан",
    adminNoUsersFound: "Пользователи по фильтрам не найдены.",
    adminPrescriptionOverview: "Обзор рецептов",
    adminPrescriptionOverviewDesc:
      "Просматривайте любые рецепты в системе и фильтруйте их по статусу или поиску.",
    adminPrescriptionStatus: "Статус рецепта",
    adminAllStatuses: "Все статусы",
    adminNoPrescriptionsFound: "Рецепты по фильтрам не найдены.",
    adminAuditLogs: "Журнал аудита",
    adminAuditLogsDesc:
      "Отслеживайте регистрацию, подтверждение, проверку, смену пароля и другие системные события.",
    adminNoLogs: "Записей аудита пока нет.",
    adminSystem: "Система",
    adminTotalUsers: "Пользователи",
    adminBlockedUsers: "Заблокированные",
  },
};

const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const stored = window.localStorage.getItem(STORAGE_KEY);

    if (stored && translations[stored]) {
      return stored;
    }

    return "uz";
  });

  const changeLanguage = (nextLanguage) => {
    if (!translations[nextLanguage]) {
      return;
    }

    window.localStorage.setItem(STORAGE_KEY, nextLanguage);
    setLanguage(nextLanguage);
  };

  const value = useMemo(
    () => ({
      language,
      changeLanguage,
      t: (key) => translations[language]?.[key] ?? translations.en[key] ?? key,
    }),
    [language]
  );

  return (
    <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);

  if (!context) {
    throw new Error("useLanguage must be used inside LanguageProvider.");
  }

  return context;
};
